spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect : org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
    generate-ddl: true

logging.level :
  org.hibernate.SQL: debug